### ISSUE TITLE
Error Pair Code, in sample: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by binnicordova** [pingidentity/pingone-mobile-sdk-android#25]
Trying with a real `pair code`, the SDK response java.lang.ArrayIndexOutOfBoundsException

```java
Error: Code=10000 "Internal Error" UserInfo={ InternalErrorCode=30000 InternalError=java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at b.b.a(PingOneSDKErrorFactory.java:18)
        at com.pingidentity.pingidsdkv2.b.a(PingOneInnerLogic.java:12)
        at a.b$a.run(CommunicationManager.java:20)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
 type=OS}
```
![Screen Shot 2022-08-04 at 10 36 42](https://user-images.githubusercontent.com/42467277/182888060-1cf57541-bd01-4ba0-8369-6e9fc9b7dda7.png)

**Comment by asafd1** [comment]
This should be fixed in the new release (1.7.2) coming up this month.
